[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "tvpaint-rpc"
dynamic = ["version"]
description = "TVPaint RPC over WebSocket server C++ plugin"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Brunch Studio Pipeline", email = "dev@brunchstudio.tv" }
]
keywords = ["tvpaint", "brunch", "tvp", "george"]

[project.urls]
Repository = "https://github.com/brunchstudio/tvpaint-rpc"
Documentation = "https://brunchstudio.github.io/pytvpaint/"

requires-python = ">=3.9"
dependencies = [
    "conan>=2.1.0",
]

[tool.hatch.version]
source = "vcs"